### ISSUE TITLE
MonadRandom instead of IO

### ISSUE THREAD

**Issue by jxv** [acowley/RANSAC#3]
Would you be open to relaxing function type sigs from `IO` to `MonadRandom` for testability? Even at some cost of performance?

**Comment by acowley** [comment]
Absolutely! Best way forward is to put in a basic benchmark so we have some idea of the performance impact and can maintain the type specialized variants if the delta is large. However, there's a reasonable chance the user's computation over the sample combined with potentially out-of-cache data loading will swamp the random number part, so I'd be fine with just cutting over to `MonadRandom` and adding specialized versions if someone finds it to be a problem.
